name:                pboy
version:             1.0.1
github:              "2mol/pboy"
license:             BSD3
author:              "Juri Chomé"
maintainer:          "juri.chome@gmail.com"
copyright:           "2018 Juri Chomé"

extra-source-files:
- README.md
- ChangeLog.md
- Spec.md

synopsis:            "a small .pdf management utility"
description: Please see the README on Github at <https://github.com/2mol/pboy#readme>

dependencies:
  - base >= 4.7 && < 5
  - text
  - containers
  - unordered-containers
  - either
  - time
  - brick
  - vty
  - fmt
  - microlens
  - microlens-th
  - filepath
  - directory
  - process
  - pdfinfo
  - vector
  - titlecase
  - htoml-megaparsec

library:
  source-dirs: src

executables:
  pboy:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - pboy

# tests:
#   pboy-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     - -Wall
#     - -Wcompat
#     - -Wincomplete-record-updates
#     - -Wincomplete-uni-patterns
#     - -Wredundant-constraints
#     dependencies:
#     - pboy
