version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - pboy-{{ checksum "pboy.cabal" }}-{{ checksum "stack.yaml" }}
      - run:
          name: Install executable
          command: stack install
      - save_cache:
          name: Cache Dependencies
          key: pboy-{{ checksum "pboy.cabal" }}-{{ checksum "stack.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
      - store_artifacts:
          path: ~/.local/bin/pboy
          destination: pboy