name: Cabal Build

# Trigger the workflow on push or pull request, but only for the master branch
on: [push, pull_request]
  # pull_request:
  #   branches: [master]
  # push:
  #   branches: [master, dev-1.4]

jobs:
  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        # cabal: ["latest"]
        # ghc: ["latest"]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1.1
      id: setup-haskell-cabal
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - uses: actions/cache@v1
      name: Cache cabal-store
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal

    - name: Build
      run: |
        mkdir bin
        cabal install --install-method=copy --installdir=bin
        ls -lh bin/
        otool -L bin/pboy || true
        ldd bin/pboy || true


    # - name: Build Linux
    #   if: matrix.os == 'ubuntu-latest'
    #   run: |
    #     cabal build all --enable-executable-static
    #     ls -l ${{ steps.setup-haskell-cabal.outputs.cabal-store }}

    # - name: Build MacOS
    #   if: matrix.os == 'macOS-latest'
    #   run: |
    #     cabal build all
    #     ls -l ${{ steps.setup-haskell-cabal.outputs.cabal-store }}


    # - name: Test
    #   run: |
    #     cabal test all --enable-tests
